version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  test:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["wait-for-it.sh", "db", "3306", "--", "pytest", "--disable-warnings", "-v"]
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}

volumes:
  mysql_data:
